// seed.js — useful sample actions for first run. Plain data, no logic.
// Public portfolio seeds only — no private host paths or internal slash routers.
export const SEED_ACTIONS = [
  {
    name: "Prompt — ask for help",
    category: "Prompts",
    type: "prompt",
    description: "Generic help scaffold for an AI chat.",
    value: "/help <describe the task, paste logs/code, or ask the question>",
    tags: ["prompt", "help"],
    favorite: true,
  },
  {
    name: "Prompt — code review",
    category: "Prompts",
    type: "prompt",
    description: "Ask for a structured review.",
    value: "/review <repo summary / pasted code / screenshot description>. Full report, end with Repair Plan + Best Next Prompt.",
    tags: ["prompt", "review"],
    favorite: true,
  },
  {
    name: "Composer — AI slash cycle",
    category: "Cursor Prompts",
    type: "composer",
    description: "Live-rotate slash tokens; pause to lock, then pick the next.",
    value: "ai",
    tags: ["composer", "slash"],
    favorite: true,
  },
  {
    name: "Git — status + last 5 commits",
    category: "Terminal Commands",
    type: "command",
    description: "Quick repo state check.",
    value: "git status && git log --oneline -5",
    tags: ["git", "status"],
    favorite: false,
  },
  {
    name: "Serve browser MCC locally",
    category: "Terminal Commands",
    type: "command",
    description: "Static UI only (no BLE).",
    value: "cd ~/hk-operator/mcc/src && python3 -m http.server 8000",
    tags: ["deploy", "local", "serve"],
    favorite: false,
  },
  {
    name: "Run MCC desktop (Tauri)",
    category: "Terminal Commands",
    type: "command",
    description: "Cyberpad-first desktop shell with BlueZ GATT.",
    value: "cd ~/hk-operator/mcc && npm install && npm run dev",
    tags: ["desktop", "tauri", "cyberpad"],
    favorite: true,
  },
  {
    name: "Cyberdeck probe — status",
    category: "Terminal Commands",
    type: "command",
    description: "BlueZ status for bonded Cyberpad (BLE name may be Cyberdeck Pad; no flash).",
    value: "cd ~/hk-operator/mcc && cargo run -p cyberdeck-probe -- status",
    tags: ["esp32", "ble", "probe"],
    favorite: false,
  },
  {
    name: "Path — HK Operator MCC",
    category: "Project Paths",
    type: "path",
    description: "Desktop companion folder in this repo.",
    value: "~/hk-operator/mcc",
    tags: ["path", "project"],
    favorite: false,
  },
  {
    name: "Path — Cyberpad hybrid firmware",
    category: "Project Paths",
    type: "path",
    description: "Cyberpad ESP32 hybrid BLE sketch.",
    value: "~/hk-operator/firmware",
    tags: ["path", "esp32", "cyberpad"],
    favorite: false,
  },
];

export const SEED_PAD_BINDINGS = {};
